### ISSUE TITLE
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed

### ISSUE THREAD

**Issue by QianyangPeng** [kno10/WikipediaEntities#1]
[WARNING] 
[WARNING] 
[WARNING] 
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:719)
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:733)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1471)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1254)
	at com.github.kno10.wikipediaentities.LuceneWikipediaIndexer$IndexHandler.rawArticle(LuceneWikipediaIndexer.java:181)
	at com.github.kno10.wikipediaentities.HandlerList.rawArticle(HandlerList.java:24)
	at com.github.kno10.wikipediaentities.ParseWikipedia$WikipediaParserThread.process(ParseWikipedia.java:254)
	at com.github.kno10.wikipediaentities.ParseWikipedia$WikipediaParserThread.run(ParseWikipedia.java:219)
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:101)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput$1.write(FSDirectory.java:271)
	at java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:73)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at org.apache.lucene.store.OutputStreamIndexOutput.writeBytes(OutputStreamIndexOutput.java:53)
	at org.apache.lucene.store.RateLimitedIndexOutput.writeBytes(RateLimitedIndexOutput.java:73)
	at org.apache.lucene.store.DataOutput.copyBytes(DataOutput.java:278)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.merge(CompressingStoredFieldsWriter.java:590)
	at org.apache.lucene.index.SegmentMerger.mergeFields(SegmentMerger.java:177)
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:83)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4089)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3664)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

**Comment by kno10** [comment]
This project will not receive any more changes.
